config/routes.rb
Bieberpong::Application.routes.draw do

  get "pages/home"
  get "scores" => 'pages#scores'

  root 'pages#home'

  namespace :game do
    get 'get_highscores', as: :get_highscores
    post 'create_highscore', as: :set_highscore
  end

end

app/models/highscore.rb
class Highscore < ActiveRecord::Base
  scope :top_ten, -> { limit(10).order('score DESC').order('created_at ASC') }

  validates :name, :country, :score, presence: true
  validates :country, inclusion: { in: %w{USA Canada} }
  validates :name, length: { minimum: 1, maximum: 11 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # http_basic_authenticate_with name: ENV['HTTP_AUTH_NAME'], password: ENV['HTTP_AUTH_PASSWORD']
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def create_highscore
    @highscore = Highscore.new(highscore_params)
    respond_to do |format|
      if @highscore.save
        @highscores = Highscore.top_ten
        @count = Highscore.count
        @data = {
          highscores: @highscores,
          count: @count
        }
        format.json { render json: @data }
      else
        format.json { render json: @highscore.errors }
      end
    end
  end

  def get_highscores
    @highscores = Highscore.top_ten
    respond_to do |format|
      format.json { render json: @highscores }
    end
  end

  private

    # Only allow a trusted parameter "white list" through.
    def highscore_params
      params.require(:highscore).permit(:name, :country, :score)
    end
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  before_action :set_highscore, only: [:show, :edit, :update, :destroy]

  # GET /highscores
  def index
    @highscores = Highscore.all
  end

  # GET /highscores/1
  def show
  end

  # GET /highscores/new
  def new
    @highscore = Highscore.new
  end

  # GET /highscores/1/edit
  def edit
  end

  # POST /highscores
  def create
    @highscore = Highscore.new(highscore_params)

    if @highscore.save
      redirect_to @highscore, notice: 'Highscore was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /highscores/1
  def update
    if @highscore.update(highscore_params)
      redirect_to @highscore, notice: 'Highscore was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /highscores/1
  def destroy
    @highscore.destroy
    redirect_to highscores_url, notice: 'Highscore was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highscore
      @highscore = Highscore.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def highscore_params
      params.require(:highscore).permit(:name, :country, :score)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @highscores = Highscore.top_ten
  end

  def scores
    if params[:page]
      @rank_offset = (params[:page].to_i - 1) * 10
    else
      @rank_offset = 0
    end
    @highscores = Highscore.order('score DESC').order('created_at ASC').paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/highscores/_form.html.erb
<%= form_for(@highscore) do |f| %>
  <% if @highscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@highscore.errors.count, "error") %> prohibited this highscore from being saved:</h2>

      <ul>
      <% @highscore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/highscores/edit.html.erb
<h1>Editing highscore</h1>

<%= render 'form' %>

<%= link_to 'Show', @highscore %> |
<%= link_to 'Back', highscores_path %>

app/views/highscores/index.html.erb
<h1>Listing highscores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @highscores.each do |highscore| %>
      <tr>
        <td><%= highscore.name %></td>
        <td><%= highscore.country %></td>
        <td><%= highscore.score %></td>
        <td><%= link_to 'Show', highscore %></td>
        <td><%= link_to 'Edit', edit_highscore_path(highscore) %></td>
        <td><%= link_to 'Destroy', highscore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highscore', new_highscore_path %>

app/views/highscores/new.html.erb
<h1>New highscore</h1>

<%= render 'form' %>

<%= link_to 'Back', highscores_path %>

app/views/highscores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @highscore.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @highscore.country %>
</p>

<p>
  <strong>Score:</strong>
  <%= @highscore.score %>
</p>

<%= link_to 'Edit', edit_highscore_path(@highscore) %> |
<%= link_to 'Back', highscores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- //////////////////////////////////////////////////////////////////////////////////////

BIEBER PONG is a personal project done for absolutely no good reason.
Bieber isn't actually a bad guy. His music is pretty good. He's just really fun to poke fun of. Love ya, Biebz!

ART DIRECTOR:     Vince Mak
COPYWRITER:       Paul Boupha
DEVELOPER:        Travis Luong

Please direct all questions or inquires to paul.boupha@gmail.com

////////////////////////////////////////////////////////////////////////////////////// -->

<html>
<head>
  <title>BIEBER PONG!!!</title>
  <meta name="description" content="Bieber Pong!!! A game where you play for keeps. Or actually, you're playing not to keep.">
  <meta name="keywords" content="justin,bieber,ping,pong,html5,game,biebz,belieber,miami,ad,school">
  <meta name="author" content="Paul Boupha, Travis Luong, Vincent Mak">
  <meta charset="UTF-8">
  <%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-17273058-9', 'bieberpong.herokuapp.com');
  ga('send', 'pageview');

</script>

<div class="socialmedia">

  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=155986774490616";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <div class="fb-like" data-href="http://www.BieberPong.com" data-width="150px" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>

  &nbsp; &nbsp;

  <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.BieberPong.com" data-text="Let's play Bieber Pong!!!" data-hashtags="bieber">Tweet</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

</div>

<div id="header">
  <%= link_to "", root_url %>
</div>

<div id="content" class="cfx">
  <%= yield %>
</div>

<div id="footer">

  A project done for no good reason by <a href="http://www.paulboupha.com">Paul Boupha</a>, <a href="http://www.travisluong.com">Travis Luong</a>, and <a href="mailto:vincentlmak@gmail.com">Vince Mak</a>.

</div>

</body>
</html>

app/views/pages/home.html.erb
<div id="stage">
</div>
<div id="high-scores">
</div>

app/views/pages/scores.html.erb
<div id="scores-nav">
  <%= will_paginate @highscores %>
</div>
<br>
<div id="high-scores">
  <table>
    <thead>
      <tr>
        <th>Rank</th>
        <th>Name</th>
        <th>Country</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @highscores.each_with_index do |highscore, idx| %>
        <tr>
          <td><%= @rank_offset + idx + 1 %></td>
          <td><%= highscore.name %></td>
          <td><%= highscore.country %></td>
          <td><%= highscore.score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>